# Generated by Django 2.2.3 on 2019-08-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190510_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reg_no',
            new_name='first_name',
        ),
    ]
