# Generated by Django 2.2.3 on 2019-08-06 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_no',
            new_name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identification_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_question',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
    ]
